### ISSUE TITLE
[TIP/REQUEST] Adding the possibility to get enchantments via a normal enchantment table

### ISSUE THREAD

**Issue by CamperSamu** [Crazy-Crew/Crazy-Enchantments#369]
Hi!
Can you please add the feature to obtain your custom enchantments via a vanilla enchantment table like Zenenchantments does?
Because I don't want to use the xp shop via /ce (or by setting Right-Click-Enchantment-Table to true) but instead I want the players to get them like normal enchantments.
Great plugin by the way!

**Comment by CamperSamu** [comment]
Adding the possibility to use a vanilla anvil would be great too!

https://github.com/Zedly/Zenchantments (Zenchantments github)

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
