### ISSUE TITLE
Add Vanilla enchant support to the crazy enchanter

### ISSUE THREAD

**Issue by HexedHero** [Crazy-Crew/Crazy-Enchantments#425]
A config option that allows users to decide if they want to use vanilla enchants inside the vanilla crazy enchantment pool.

The Vanilla books from the crazy enchanter or from lost books would behave the same as the custom enchant books.

This would allow for people to ONLY use the crazy enchanter, instead of relying on the vanilla enchanting table for vanilla enchants.

**(e.g when you use the right-click enchantment table config setting it makes sense.)**

**Comment by Ghostipedia** [comment]
+1 - This feature would be greatly appreciated - I just recently brought this up in the Discord server, I feel like it'd be a great addition.

**Comment by Kr1stuX** [comment]
+1 - Would love to see this

**Comment by MrApocalyptic** [comment]
+1 - Yeah thatd be lit

**Comment by Replacers** [comment]
+1 - This would be an amazing addition; We all hope to see it soon!

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
