### ISSUE TITLE
Completely Unbreaking

### ISSUE THREAD

**Issue by djkittycoolcat** [Crazy-Crew/Crazy-Enchantments#434]
I apologize for posting twice, however, I wanted to keep the suggestions separate. Is it possible to make an 'unbreaking' type enchant where the tool/armor never breaks, basically indestructible?

Thank you so much! We bought a premium plugin, however, ended up deciding that this one is much better!

**Comment by minejango2** [comment]
It this still working?

**Comment by badbones69** [comment]
Working no as it hasn't been added but is still a possible thing Ill add later.

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
