### ISSUE TITLE
Suggestions - Tab complete option/Permission Node to match AND Restrict Max level

### ISSUE THREAD

**Issue by EchocallingEarth** [Crazy-Crew/Crazy-Enchantments#466]
The following are two suggestions I have that may make the plugin 100 times better and easier to use. The first includes a permission node section as this is just as important as the suggestion. The second is a suggestion that may have been implemented and I did not see how to use or set it.

First "Tab complete option/Permission Node"
When using _**/ce book**_ the admin or person using this must know the name of the book they are looking for otherwise it is a guessing game.

Please add an option that would allow tab-complete of this section. This means the person would be able to use _/ce book_ and press tab to see a list of all possible books. They would still need to select the level. But at least they would not be guess working what books are available. This is very useful as there are 80 plus options and that makes guessing very hard.

Also, make a permission node for this so that it could be restricted to admins only.

----

For the second part "Restricting Max Level" 
May I suggest setting a max level of enchantment that can be created. For example, I tested and made a level 9999 AcidRain Book just to see if I could(note I am the Owner). This is crazy high. Can you set a restriction of say max level 10 (or X)? This may also include a separate permission node that would allow admin bypass or player bypass depending on the choice of the server owner/admin team. 

If the second option is possible already please instruct me on how this would be possible to set.
Should my suggestions need more info please let me know and I will do my best to provide as much helpful info as I can.

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
