### ISSUE TITLE
percentage suggestion - lock enchantment

### ISSUE THREAD

**Issue by minejango2** [Crazy-Crew/Crazy-Enchantments#473]
percentage suggestion - lock enchantment percentage

**Comment by badbones69** [comment]
Can you explain?

**Comment by minejango2** [comment]
lock percentage crazy enchant books, so non-op user cannot edit percentage.

**Comment by badbones69** [comment]
Ah, well this could be something I might add as I do see a use for this.

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
