### ISSUE TITLE
Suggestion: Tinker Vanilla Enchantment Books 

### ISSUE THREAD

**Issue by Thesense1** [Crazy-Crew/Crazy-Enchantments#495]
An Option to make it possible to Tinker Vanilla Enchantment Books to get currency from them. The same like it behaves with Enchantments on Armor.

Basically on my server many people are doing AFK Fishing to get enchanted armor from it to tinker it. You also get many enchanted books you mostly dont even need. At this point you just throw them away. If you could tinker them it would make sense to keep them.

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
