### ISSUE TITLE
Memory problem?

### ISSUE THREAD

**Issue by hkkongou** [Crazy-Crew/Crazy-Enchantments#496]
Hi, i am facing some memory problem with this plugin, when i enabled this plugin , the minecraft server memory stats shows the memory rise up very fast (slope almost verticle), when i disabled this plugin, the memory stats slope is like y=x.
The problem is that tps becomes unstable , i tried to use timings to check and i found out that packet event maybe making the server lag. I tried to disable some of the enchantments but seems not working. I am using default config that generates when the game load.

**Versions :**
 - Minecraft Server Version: paper 168 1.15.2
 - Plugin Version: v1.8 Dev Build v8

**Issue**
Timings:
https://timings.aikar.co/?id=69673c97b2384a2886523fcc839a1c02
Tps drop and tps loss when crazyenchantment is enabled (using plugman)

**Screenshots**
![image](https://user-images.githubusercontent.com/61608872/79034274-4bf17a80-7be7-11ea-9857-8c4cab0908a6.png)

**Comment by badbones69** [comment]
There has been some work to the enchantment optimization in the current Jenkins builds. You could try those out and see if it helps.

https://jenkins.badbones69.com/

**Comment by hkkongou** [comment]
> There has been some work to the enchantment optimization in the current Jenkins builds. You could try those out and see if it helps.
> 
> https://jenkins.badbones69.com/
I upgraded to the latest jenkins build, however i saw this bug :<

![image](https://user-images.githubusercontent.com/61608872/79177768-2ad29900-7e36-11ea-904e-d54fb348a102.png)

**Comment by badbones69** [comment]
Just fixed: 81d66bc534458ee7f6e70e5e1c4e3d066fea2c06

**Comment by hkkongou** [comment]
> Just fixed: [81d66bc](https://github.com/badbones69/Crazy-Enchantments/commit/81d66bc534458ee7f6e70e5e1c4e3d066fea2c06)
Hi, the error message is gone which is nice.
The memory problem have little bit better i think, however this is the memory graph when im using

Minecraft Server Version: paper 184 1.15.2
Plugin Version: v1.8 Dev Build v8 #127 
Is still not that good :< , the graph below shows that i have 22~ players and the memory still rise up so fast.
I guess this plugin needs a lot of listener to make enchantment works. I saw each time when a player join, the memory become much steeper, (timings shows playerjoinevent somhow lag.)

Please continue to optimize the plugin, thank you 
 
![image](https://user-images.githubusercontent.com/61608872/79428287-89477500-7ff8-11ea-9b89-4578686d7064.png)

**Comment by hkkongou** [comment]
> Just fixed: [81d66bc](https://github.com/badbones69/Crazy-Enchantments/commit/81d66bc534458ee7f6e70e5e1c4e3d066fea2c06)
New bug found seems like :<
![image](https://user-images.githubusercontent.com/61608872/79564170-b4a58f00-80e0-11ea-943e-ec91806a4a77.png)

**Comment by badbones69** [comment]
Could you try the newest build and let me know if it still errors.

**Comment by hkkongou** [comment]
> Could you try the newest build and let me know if it still errors.

Unfortunely, i cannot catch up your update since im opening my server almost 24/7 
I updated the latest build #131 this morning (UTC+8HK time) and you released #132-#134 🤔 within 10 hours , is good to have new update tho, but i may need to try tomorrow after update the latest snapshot
![image](https://user-images.githubusercontent.com/61608872/80106781-dd2ffc00-85ac-11ea-929e-302de637f772.png)

**Comment by hkkongou** [comment]
#134 have problem 
![image](https://user-images.githubusercontent.com/61608872/80195903-259ff600-864f-11ea-9753-c863ae61c276.png)

**Comment by hkkongou** [comment]
> Could you try the newest build and let me know if it still errors.
serious problem
tps 9 
![image](https://user-images.githubusercontent.com/61608872/80216291-69efbe00-8670-11ea-9b0a-64cc14ac97f7.png)

**Comment by hkkongou** [comment]
found this bug happens when citizen sentinel npc took crazy enchantment weapon and use it for attacking others
eg sword.

**Comment by badbones69** [comment]
Just pushed a possible fix for the NPE from getEnchantmentsOnItem.
Commit: ab39823d3e775403876ba307b819a204f73a8c18

This should fix the citizen's NPE.
087ede7bd510b936221cb6a6b077bb3a4427df99

**Comment by hkkongou** [comment]
> Just pushed a possible fix for the NPE from getEnchantmentsOnItem.
> Commit: [ab39823](https://github.com/badbones69/Crazy-Enchantments/commit/ab39823d3e775403876ba307b819a204f73a8c18)
> 
> This should fix the citizen's NPE.
> [087ede7](https://github.com/badbones69/Crazy-Enchantments/commit/087ede7bd510b936221cb6a6b077bb3a4427df99)

![image](https://user-images.githubusercontent.com/61608872/80296079-b808dc80-87aa-11ea-9d24-180ca25ff855.png)
got very big problem
spam error message until disabled plugin
![image](https://user-images.githubusercontent.com/61608872/80296112-e38bc700-87aa-11ea-8040-bca4e28189e5.png)

**Comment by badbones69** [comment]
could you pastbin the log as it isnt showing the error there.

**Comment by hkkongou** [comment]
> could you pastbin the log as it isnt showing the error there.

i send the entire log to you then.
it reaches pastebin limit and i can't paste it , instead 
https://drive.google.com/file/d/1at_g7nhTzaIhoLf0xhMd0aScLeHYGn3t/view?usp=sharing

**Comment by badbones69** [comment]
Do you know when this happens?

**Comment by hkkongou** [comment]
> Do you know when this happens?

No, If i have found this problem again, i post here then.
However, this is not the main problem that i want to raise in this thread :(

The problem that im always concerning is the Ram usage and how it make TPS low :(

**Comment by hkkongou** [comment]
> Do you know when this happens?

Got something new bug ? happening 🤔 
![image](https://user-images.githubusercontent.com/61608872/80566160-e5f95580-8a24-11ea-8da8-75996412fb17.png)

**Comment by hkkongou** [comment]
> Do you know when this happens?
got new bug
CE # 142 
![image](https://user-images.githubusercontent.com/61608872/82559907-fbd0e500-9ba2-11ea-8f5f-43a94721a850.png)
