### ISSUE TITLE
[Bug Report] Multiple Issues with Telepathy Enchant

### ISSUE THREAD

**Issue by SavagePanda116** [Crazy-Crew/Crazy-Enchantments#515]
Some issues with Telepathy:
- Doesn't work with vanilla enchants, like Fortune and Silk Touch.
- Allows players to duplicate items. For example, with Telepathy on an axe, if a player breaks a bed or a sign, the item will be placed in their inventory (as telepathy should work), but the item still also drops on the ground, so the player can receive two.
- Allows players to break items in world guard regions even with all build/block-break related options set to deny. 

 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#141

**Comment by RyderBelserion** [comment]
The bug report is not being ignored, Moved to a tracking board which will be added to the README.
