### ISSUE TITLE
[Bug Report] Blast Enchant not compatible with Durability Alerts

### ISSUE THREAD

**Issue by SavagePanda116** [Crazy-Crew/Crazy-Enchantments#516]
Player's items with the Blast Enchant break very quickly and most don't notice when they are low-durability and are losing a lot of expensive-to-make items. We've added a Durability Alert plugin on our server to try to help with this, and it is working with all items/enchants EXCEPT Blast, of course. 

I spoke with the Durability Alert developer first and they took a look at the source code for Crazy Enchantments and said that " it appears that they aren't calling the function to break the block properly". I hope that this is something that can be fixed, it would be really helpful for us! 

 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#141

**Comment by Hitosherizu** [comment]
Blast-Full-Durability: true #Toggle if the item takes damage for every block it breaks or just one. True to take full damage or false to take only 1 damage.

**Comment by SavagePanda116** [comment]
I think changing this setting to false is making items with Blast take damage slower so that they last longer, but I'm not sure how I feel about that :P.

Making that change still didn't working with our Durability Alerts. The dev looked at this source code and said that this plugin isn't calling the "block break" function properly for the alerts to work with this enchant.

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
