### ISSUE TITLE
[Bug Report] AAC + Blast Miner

### ISSUE THREAD

**Issue by minemalia** [Crazy-Crew/Crazy-Enchantments#526]
Hey,

I am using
 -  paper 1.15.2
 - Crazyenchantments 1.8-Dev-Build-v8-RELEASE
 - AAC 4.3.12 (default configuration)

Issue: When using a pickaxe with blast enchantment 2 or 3, AAC will kick the player because of the player is 'breaking blocks too quickly'. Blast enchantment 1 is blocked too by AAC,  but the player will not get kicked.

Screenshots: https://imgur.com/41lLCJW

Would be nice if this can be fixed.

Thanks in advance!

**Comment by PhoenixHaven** [comment]
You'll most likely have to disable the check as there probably isnt much badbones can do as that's the nature of the ce.

**Comment by minemalia** [comment]
Similar enchantment with tokenenchant, https://www.mc-market.org/resources/14045/, aren't blocked by AAC.

For example the Excavation tokenenchant which is exactly the same as Blaste, isn't blocked by AAC.
The tokenenchant sphered, explosive and tile enchants also don't cause problems with AAC.

**Comment by RyderBelserion** [comment]
AAC has been abandoned.
