### ISSUE TITLE
[Feature Request] Add FarmLand Block to PLANTER Enchantment

### ISSUE THREAD

**Issue by Xuwznln** [Crazy-Crew/Crazy-Enchantments#528]
As the title shows.

**Comment by Xuwznln** [comment]
I think I missed something. Planter only have one level. I hope this can be multi-level and increase the radius of planting. Right click dirt/grass_block/farmland will just make effect. I am wondering if it could be added in the future build. Thanks.

**Comment by RyderBelserion** [comment]
The suggestion is not declined, Moved to a tracking board which will be added to the README.
