### ISSUE TITLE
[Bug Report] PlotSquared Interaction Console Error

### ISSUE THREAD

**Issue by elsell** [Crazy-Crew/Crazy-Enchantments#532]
**Describe the bug**
Error Spam in Console

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.15.2
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#141

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/159QN1A2

**Issue**
Error Spam in Console

**Screenshots**
All I have is the error in the console.

**Comment by RyderBelserion** [comment]
https://github.com/Crazy-Crew/Crazy-Enchantments/releases/tag/1.9.1
