### ISSUE TITLE
[Suggestion] Mutually exclusive 

### ISSUE THREAD

**Issue by wsman217** [Crazy-Crew/Crazy-Enchantments#542]
A pretty cool and useful feature would be to have it be possible to have CE's be mutually exclusive with both other CE's and normal enchantments. This could either be hard coded or configurable I feel that the latter would be the more appreciated version.

**Comment by badbones69** [comment]
Could you explain more to me?

**Comment by wsman217** [comment]
Like where you can't have silk touch and fortune on a pickaxe.
