### ISSUE TITLE
CE Enchant duplication, CE book and lore not match, CE performance probem

### ISSUE THREAD

**Issue by hkkongou** [Crazy-Crew/Crazy-Enchantments#544]
1 CE enchant will duplicate itself when a new CE enchant is added in or restart server 
2 CE book lore does not match CE books' name usually occurs when server is restarted.
3 CE is installing too much listener on players? if the server have too many players , listeners will stress the server ram and cpu alot, it uses so much ram and makes the cpu and java need to frequently do garbage collections

Paper 1.15.2 324
CE DEV 1.15.2 8.1 #150

There is no error message shown in log 
However, timings do show CE heavy load

https://cdn.discordapp.com/attachments/696002416239444008/740524264784134255/m.png

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
