### ISSUE TITLE
[Bug Report] Totem of Undying reset all armor effects

### ISSUE THREAD

**Issue by Futurixel** [Crazy-Crew/Crazy-Enchantments#549]
**Describe the bug**
When a Totem of Undying is activated, it removes all the effects added by the Custom Enchants.

The player have to remove and put his armor back on for the effects to return.

**Versions:**
 - Minecraft Server Version: [1.16.2]
 - Plugin Version: [1.8-Dev-Build-v8.1-SNAPSHOT-Build#152]

**Comment by slitherskull200** [comment]
its a normal thing totems do, they remove all your affects but it would be better if the plugin could track a totem is used and automaticly reset the affects

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
