### ISSUE TITLE
[Bug Report] Error of Blast and Telepathy

### ISSUE THREAD

**Issue by aSaPedoPhi08** [Crazy-Crew/Crazy-Enchantments#556]
**Describe the bug**
Blast and Telepathy can copy block.
**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.3
 - Plugin Version: Crazy-Enchantments-152  server:paper-136 (1.16.3)

**Pastebin any errors in console**
None
But there have a vedio to show how it happene : https://youtu.be/BqhzJkhUs-s
In vedio who used nethertite_pickaxe which have BlastLv3 and Telepathy to distroy 6 block of ancient_block.
But he actually get 12 ancient_block.

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.

**Comment by Av1vxBan** [comment]
I got the same bug is it still a bug 2.4.1 is my version
