### ISSUE TITLE
[Bug Report] Dupe Glitch

### ISSUE THREAD

**Issue by qSeek** [Crazy-Crew/Crazy-Enchantments#563]
**Describe the bug**
Breaking Doors and Beds with Telepathy duplicates them.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.3
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#156

**Pastebin any errors in console**
Link: -

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
