### ISSUE TITLE
[Bug Report] KingdomsX

### ISSUE THREAD

**Issue by MrSuricate2** [Crazy-Crew/Crazy-Enchantments#565]
**Describe the bug**
When a player fights another player the error message appears

**Versions (please complete the following information):**
 - Minecraft Server Version: [1.13.2]
 - Plugin Version: [1.8-Dev-Build-v8.1-SNAPSHOT-Build#157]

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/dexK5W9H

**Issue**
This spam the error console

**Comment by RyderBelserion** [comment]
https://github.com/Crazy-Crew/Crazy-Enchantments/issues/543
