### ISSUE TITLE
Mixing fortune telepathy and furnace causes only one item to drop per ore.  

### ISSUE THREAD

**Issue by Klawdek** [Crazy-Crew/Crazy-Enchantments#567]
**Describe the bug**
If you have Fortune III + Telepathy I + Furnace I on a pickaxe it will cause ores to drop only 1 ore when mining diamond
I also tested just the combo of Telepathy and Furnace and it caused Lapis Lazuli Ore to only drop 1.

Also some other combinations produce some numbers that may need to be looked at.
In the screenshot below, note the numbers for the 

Fortune III + Telepathy I + Furnace I
Fortune III + Telepathy I
Fortune III + Autosmelt V

And note the numbers for lapsis Lazuli with Telepathy and furnace.

**Versions (please complete the following information):**
 - Minecraft Server Version: git-Paper-384 (MC: 1.15.2)
 - Plugin Version: 1.8-Dev-Build-v8-RELEASE

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/

**Issue**
Describe the issue you are having with the plugin.

**Screenshots**

Here is screenshot of my tests where I broke 25 blocks 3 times for each test.  
![Screenshot (2204)](https://user-images.githubusercontent.com/45950944/102568103-7c5bb380-40a8-11eb-8682-4431c3f6f666.png)

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
