### ISSUE TITLE
Furnace and AutoSmelt

### ISSUE THREAD

**Issue by Runeeeee** [Crazy-Crew/Crazy-Enchantments#582]
Furnace Enchant and AutoSmelt Enchant doesn't work on Ancient Debris.
I tried mining Ancient Debris with Furnace / AutoSmelt Enchant but to no avail it doesn't work.
But it does work as usual on other ores.

 - Minecraft Server Version: 1.16.4
 - Plugin Version: 1.8-Dev-Build-v8.1-SNAPSHOT-Build#164

**Comment by RyderBelserion** [comment]
Added in latest release
