### ISSUE TITLE
Self-Destruct does not work.

### ISSUE THREAD

**Issue by Klawdek** [Crazy-Crew/Crazy-Enchantments#583]
**Describe the bug**

When player is killed while wearing armor with Self-Destruct there is not explosion and they can go back and get the armor with Self-Destruct on it.

**Versions (please complete the following information):**
 - Minecraft Server Version: [e.g. 1.8.8]  Paper version git-Paper-351 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

 - Plugin Version: [e.g. 1.7.9.4] 
version §a1.8-Dev-Build-v8.1-SNAPSHOT-Build#164

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://pastebin.com/

**Issue**
Describe the issue you are having with the plugin.

**Screenshots**

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
