### ISSUE TITLE
[Bug Report] Better performance

### ISSUE THREAD

**Issue by bobhenl** [Crazy-Crew/Crazy-Enchantments#584]
**Describe the bug**

**Versions (please complete the following information):**
 - Minecraft Server Version 1.16.5
 - Plugin Version: build 158

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Issue**
Hi, I have several lags caused also by this plugin. I know that this plugin doesn't have the biggest impact, but it still could be a little bit better.

https://spark.lucko.me/#CSNSYiDThY
https://spark.lucko.me/#MuzREldpav -> 5 minutes
https://timings.aikar.co/?id=d7d5325a26f14d348f0559dc45bfe2ca

**Comment by elmaslarry** [comment]
I have the same issue on Plugin Version: build 168

also this errors:
https://paste.md-5.net/iyuvewuteh.bash

**Comment by ComPieter1** [comment]
Can confirm with TPS drops and stack traces/NPE errors.

**Comment by srnyx** [comment]
Any update on this?

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
