### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by elmaslarry** [Crazy-Crew/Crazy-Enchantments#585]
**Describe the bug**
Plugin is constantly spamming errors and warnings in console

**Versions**
 - Minecraft Server Version: 1.16.5 paper (
 - Plugin Version: CrazyEnchantments[v1.8-Dev-Build-v8.1-SNAPSHOT].jar (#168 from jekins)

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://paste.md-5.net/dafeyuhuno.pl

**Issue**
Plugin also have bad performance, it consume too much resources. 
Timings: https://timings.aikar.co/?id=cfe6279a2268431f9e938938369ef09f#plugins
Spark sampler: https://spark.lucko.me/#uD95r3fWQK

**Comment by elmaslarry** [comment]
good work!

**Comment by elmaslarry** [comment]
F

**Comment by RyderBelserion** [comment]
Try updating to the latest jenkins build

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
