### ISSUE TITLE
[Bug Report] issue with Towny - isFriendly method

### ISSUE THREAD

**Issue by Zimoune** [Crazy-Crew/Crazy-Enchantments#587]
**Describe the bug**
TownySupport.isFriendly method is incompatible with latests Towny version

**Versions:**
 - Minecraft Server Version: 1.16.5 paper-437
 - Plugin Version: Crazy Enchantments v1.8 Dev Build v9
 - Towny Version: 0.96.7.7

**Pastebin any errors in console**
Link: https://pastebin.com/35NAMLGJ

**Issue**
Console is spamming errors on PlayerMoveEvent with Towny.
Method CombatUtil.preventDamageCall takes now 4 parameters.

**Screenshots**
![2021-04-01_18h50_29](https://user-images.githubusercontent.com/6942133/113327404-335c0200-931b-11eb-9d19-9d7cafe48eeb.png)
Towny Javadoc:
![towny-javadoc](https://user-images.githubusercontent.com/6942133/113328385-84202a80-931c-11eb-8801-b70d2aae1f33.png)

**Comment by RyderBelserion** [comment]
Fixed in v1.9.1
