### ISSUE TITLE
TPS drops

### ISSUE THREAD

**Issue by xgab05x** [Crazy-Crew/Crazy-Enchantments#591]
Hi. i've a problem, Crazyenchantments cause big TPS drops in my servers, Checking with Timings i found that TPS drops are caused by CrazyEnchantments::Event: m.b.c.e.AllyEnchantments (EntityDamageByEntityEvent)

Can you fix this issue? Thanks a lot

**Comment by ad1tya2** [comment]
Same issue here,
Need a fix soon if possible

**Comment by ad1tya2** [comment]
@xgab05x are you also running mcmmo?

**Comment by RyderBelserion** [comment]
Can you run a timings and send it here?

**Comment by xgab05x** [comment]
> @xgab05x are you also running mcmmo?

i tried deleting mcmmo but nothing changes

**Comment by xgab05x** [comment]
> Can you run a timings and send it here?

https://timings.aikar.co/?id=267d399f37194adaab0bef6d1696fecd#timings

**Comment by slitherskull200** [comment]
strange, i dont seem to be getting this issue and i am running crazyenchantments mcmmo and like 50 other plugins. the only tps drops that ever happen are the ones when the server starts when the tps drops to 19.92

**Comment by ad1tya2** [comment]
can you give your server and plugins version info maybe?

**Comment by slitherskull200** [comment]
im using paper 1.17.1 with v9 dev build of ce

**Comment by ad1tya2** [comment]
mcmmo?

**Comment by slitherskull200** [comment]
yes

**Comment by ad1tya2** [comment]
mcmmo version?

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
