### ISSUE TITLE
Error spam in the console

### ISSUE THREAD

**Issue by srrawr11** [Crazy-Crew/Crazy-Enchantments#593]
I have a spam in the console..
https://pastebin.com/beiGRXky

Using the latest version of CE from Spigot.
Version: v1.8 Dev Build v9 Update
Using in paper 1.8.8.

**Comment by srrawr11** [comment]
It drops the tps as well..
![image](https://user-images.githubusercontent.com/73607495/119066284-59c32300-b9d7-11eb-87ff-4c36416795fa.png)


Using the latest version of CE from Spigot.
Version: v1.8 Dev Build v9 Update
Using in paper 1.16.5.

**Comment by RyderBelserion** [comment]
Please update to the latest build on the jenkins - https://jenkins.badbones69.com/job/Crazy-Enchantments/

**Comment by srrawr11** [comment]
I have already used it for 1.8.8 but same problem, as I sent you a console spam.
