### ISSUE TITLE
[Bug Report] Error with kingdoms

### ISSUE THREAD

**Issue by winnipeg21** [Crazy-Crew/Crazy-Enchantments#594]
**Describe the bug**
Pull enchant (maybe all) isn't working with KingdomsX

**Versions (please complete the following information):**
 - Purpur #1127 (1.16.5)
- 1.8 Dev-Build-v9-Build#173
- Kingdoms 1.10.19

**Pastebin any errors in console**
https://pastebin.com/dYmJ5nT0

**Issue**
I try using the Pull enchantment but it doesn't work and I get spammed with the error in console.

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
