### ISSUE TITLE
[Bug Report] Enchants not applying

### ISSUE THREAD

**Issue by winnipeg21** [Crazy-Crew/Crazy-Enchantments#596]
**Describe the bug**
Enchants not applying

**Versions (please complete the following information):**
 - Purpur #1127 (1.16.5)
- 1.8 Dev-Build-v9-Build#173
- Kingdoms 1.10.19

**Pastebin any errors in console**
No error in console

**Issue**
When you set `BookColor` to have `&r` to stop the italics the enchant book can't be applied to any item. The book just acts a normal item

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
