### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by ax3lt** [Crazy-Crew/Crazy-Enchantments#597]
SilkSpawner issue

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5
 - Plugin Version: v1.8-Dev-Build-v9-RELEASE

https://hastebin.com/iducirixov.md

Basically it fails to start if silkspawners starts before it, if I disable silkspawner and load crazyenchatments and then again silkspawners goes

**Comment by AirCraze** [comment]
I agree. Same exact issue here.

Version: Paper 1.16.5

**Comment by ax3lt** [comment]
Bump

**Comment by AirCraze** [comment]
I tried downgrading. However cannot, since I'm using 1.16.5.
This issue seems to happening on 1.16.5 and higher.

**Comment by ax3lt** [comment]
Author?
