### ISSUE TITLE
Lands compatibility

### ISSUE THREAD

**Issue by srnyx** [Crazy-Crew/Crazy-Enchantments#601]
Will you be adding compatibility for [Lands](https://www.spigotmc.org/resources/53313)?

**Comment by srnyx** [comment]
@badbones69

**Comment by RyderBelserion** [comment]
Yes

**Comment by srnyx** [comment]
> Yes

Is that a "Yes, I've done it" or "Yes, I will eventually"?

**Comment by srnyx** [comment]
> > Yes
> 
> Is that a "Yes, I've done it" or "Yes, I will eventually"? lol

@badbones69 @RyderBelserion

**Comment by RyderBelserion** [comment]
It's not forgotten. its just there more then one plugin to maintain. I am currently focused only on CrazyCrates

**Comment by srnyx** [comment]
> It's not forgotten. its just there more then one plugin to maintain. I am currently focused only on CrazyCrates

Wouldn't you want to keep the issue open though as it isn't resolved/done yet?
