### ISSUE TITLE
[Bug Report] CE MythicMobs compatibility and Spam excptions!

### ISSUE THREAD

**Issue by elmaslarry** [Crazy-Crew/Crazy-Enchantments#607]
**Describe the bug**
Spamming exceptions and errors in console

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5 paper
 - Plugin Version: CrazyEnchantments version 1.8-Dev-Build-v10-Build#174

*Do **NOT** say Latest use `/version crazyenchantments` in the console.

**Pastebin any errors in console**
Link: https://paste.md-5.net/izohaguwah.cs

**Issue**
I think the error comes to mythicmobs mobs that are attacked with weapons enchanted by CE, if you could fix or add compatibility to MM will be nice, btw i dont know certainly if the issue is related to MM plugin!

**Screenshots**
Dont have!

**Comment by wsman217** [comment]
We have already asked you to provide a copy of your latest.logs

**Comment by elmaslarry** [comment]
[latest.log](https://github.com/badbones69/Crazy-Enchantments/files/6834044/latest.log)

**Comment by wsman217** [comment]
Please use a pastebin we do not want to download a possibly malicious file to our devices

**Comment by elmaslarry** [comment]
https://paste.md-5.net/epidedeyen.makefile

**Comment by wsman217** [comment]
It looks like a piece of armor that your players are wearing is causing an issue in how the plugin checks the enchantments.

**Comment by wsman217** [comment]
Try disabling the Stormcaller enchantment to see if that fixes it

**Comment by elmaslarry** [comment]
what piece? how can found it?

**Comment by RyderBelserion** [comment]
Added to list of things to check
