### ISSUE TITLE
Cant perform /ce

### ISSUE THREAD

**Issue by slitherskull200** [Crazy-Crew/Crazy-Enchantments#610]
**When i use /ce it says an internal error occurred while attempting to perform this command**

 - 1.17.1
 - Plugin Version: v1.8 Dev Build

https://pastebin.com/EHxwcyuL

**Issue**
if i type /ce it returns me with An internal error occured while attempting to perform this command and the error looks like it says that the plugin is disabled when i checked and its still enabled 

**Screenshots**
![image](https://user-images.githubusercontent.com/73899537/127849397-978cd619-dd77-4499-b9a2-4da86c13b750.png)

**Comment by Samet93** [comment]
unfortunately this happens to me too
