### ISSUE TITLE
Can't disable enchantments

### ISSUE THREAD

**Issue by antebell** [Crazy-Crew/Crazy-Enchantments#613]
Whenever I disable enchantments via the config, anytime I try to buy enchantments from any category; it says there's no enchantments assigned to the categories.

 - Minecraft Server Version: 1.17.1
 - Plugin Version: Dev Build v10

**Screenshots**
![screen](https://user-images.githubusercontent.com/79293014/128564753-7c8672c1-4210-429a-b0dc-7293ef15e6ce.png)

**Comment by gm1224** [comment]
Go into Enchantments.yml, find the enchantment you wish to disable and set "Enabled" to false. You must have messed with something else as I can't seem to replicate this.
