### ISSUE TITLE
[Bug Report] Walking enchants don't work

### ISSUE THREAD

**Issue by srnyx** [Crazy-Crew/Crazy-Enchantments#614]
**Describe the bug**
Any enchant that requires walking doesn't work (i.e. Nursery, HellForged, Implants)

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5
 - Plugin Version: 1.8-Dev-Build-v9-Build#173

**Console error:**
https://paste.srnyx.xyz/dinivihako.csharp
https://paste.srnyx.xyz/mukeduxoca.csharp

**Comment by nissiongot** [comment]
Im having the same error

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
