### ISSUE TITLE
[SUGGESTION] Improve Spartan compatibility

### ISSUE THREAD

**Issue by srnyx** [Crazy-Crew/Crazy-Enchantments#615]
Can you make it so that it will do less false positives with [Spartan Anti Cheat](https://www.spigotmc.org/resources/25638)?
Mainly with things like jump boosts and speed boosts.

**Comment by RyderBelserion** [comment]
https://github.com/Crazy-Crew/Crazy-Enchantments/releases/tag/1.9.1
