### ISSUE TITLE
[Bug Report] People can use black smith to make god armor

### ISSUE THREAD

**Issue by srnyx** [Crazy-Crew/Crazy-Enchantments#616]
**Describe the bug**
People can use the black smith to add all the vanilla protections to 1 armor piece (and infinity/mending bow, smite/sharpness sword, etc...)

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5
 - Plugin Version: 1.8-Dev-Build-v9-Build#173

**Issue**
People can use the plugin to cheat the system

**Screenshots**
![img](https://go-to.srnyx.xyz/r/ksddxs9g49a)
![img](https://srnyx.is-from.space/r/ksddy1amh9a)
![img](https://img.srnyx.xyz/r/ksddym60b9a)

**Comment by RyderBelserion** [comment]
Can you elaborate? The screenshots are gone.

**Comment by srnyx** [comment]
> Can you elaborate? The screenshots are gone.

You're able to combine armor that had Protection and another piece of armor that had Projectile Protection which would get you Protection and Projectile Projection on the same armor piece. It works with any type of protection and any type of armor. You're able to get all protection enchants on all of your armor if you do it right.

**Comment by RyderBelserion** [comment]
Added to our new bug tracker.
