### ISSUE TITLE
[Bug Report] Can't use /ce Command

### ISSUE THREAD

**Issue by Xsro123** [Crazy-Crew/Crazy-Enchantments#618]
The /ce Command does NOT work.

 - Minecraft Server Version: 1.17.1
 - Plugin Version: Minehut

/ce does not work

**Comment by Xsro123** [comment]
PLease help

**Comment by slitherskull200** [comment]
have the same issue with 1.17, i am just testing 1.16.5 because that worked for me a while ago

**Comment by gm1224** [comment]
Are you using the most recent build? If so, does console show any errors related to the execution of the command?

**Comment by kingelectrixgyt** [comment]
> Are you using the most recent build? If so, does console show any errors related to the execution of the command?

I have the same problem but I’m getting a zip file closed error

**Comment by kingelectrixgyt** [comment]
I have the latest version on the GitHub repository and am on version 1.16.5
