### ISSUE TITLE
SilkSpawners and Crazyenchantments compatibility

### ISSUE THREAD

**Issue by ZDaPlaY** [Crazy-Crew/Crazy-Enchantments#623]
Can crazyenchantments add support for SilkSpawners?
I think SilkSpawners makes the plugin load after
CrazyEnchantments version 1.8-Dev-Build-v10-Build#174
1.17.1
SilkSpawners version 7.1.0

**Comment by RyderBelserion** [comment]
SilkSpawners support is busted and I have no idea why, It'll be looked into but for now. You have to either downgrade or use another plugin like WildStackers. They have it available for free.
