### ISSUE TITLE
big max level of enchantment crashes server 

### ISSUE THREAD

**Issue by amp7368** [Crazy-Crew/Crazy-Enchantments#629]
**Describe the bug**
If the max level of an enchantment is set to a big number, it crashes the server

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.17.1
 - Plugin Version: 1.8

**Pastebin any errors in console**
The error in console is just a long stacktrace of shutting down

**Issue**
In CETab.java, there are several for loops that simply adds a completion for each possible value a user could enter for a level
A number like 1,000,000 for a maxLevel will make this loop run a million times to do tab completions and crash the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/47309189/134777762-4af3c785-8316-4b91-be63-8c2d47065d35.png)

**Comment by RyderBelserion** [comment]
This will be addressed, Commands are being completely re-written soon
