### ISSUE TITLE
[Suggestion] Empty Slot Option in Crates

### ISSUE THREAD

**Issue by Revanrose6** [Crazy-Crew/Crazy-Enchantments#634]
**Describe the Problem**
If a crate gives more than 1 reward or multiple stacks of a reward and they don't have enough inventory space, the reward beyond the 1 empty slot disappears. 

**Suggestion**
Add a part of the config or the crate configs to determine the minimum amount of empty slots for crate use. Some of my crates for instance, only have 1 item. Others drop multiple stacks. If there was a config option like
EmptySlots: 3 

which I could use to determine that you are required 3 empty slots to be able to use that crate, I think that would be an improvement. 

**Screenshots**

**Comment by RyderBelserion** [comment]
This is the wrong project. Post this in [Crazy-Crates ](https://github.com/Crazy-Crew/Crazy-Crates/issues)
