### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Anhrak** [Crazy-Crew/Crazy-Enchantments#637]
With the 1.17 / 1.18 way that handles ores, I'd love to see an enchantment that converts Raw Copper, Raw Iron, Raw Gold (but also other items like Diamond, Coal, Redstone, Lapis and Emerald) into its Block variant if you have 9 in your inventory upon mining.

**Comment by RyderBelserion** [comment]
Added to our suggestions board
