### ISSUE TITLE
[DROP TPS + SUGGESTION] 

### ISSUE THREAD

**Issue by srrawr11** [Crazy-Crew/Crazy-Enchantments#638]
Minecraft Java Edition
Version of MC: Paper 1.16.5
Version of the plugin: Latest Dev Build

Suggestion:
Hi, hope you are doing well.
I have a big problem and it's that drops the tps of my server too much, I think is the particles from some enchantments.
If you could add any section for deactivate them.. the perfomance will be much better than before.

Here is the timing from my server..
![image](https://user-images.githubusercontent.com/73607495/144933707-098f4abe-6dde-44e0-b18e-49389b32783d.png)

I have been reporting these like 3 months ago.. but no one answered me.
Thanks for your attention. Keep safe!

**Comment by RyderBelserion** [comment]
Will be addressed

**Comment by RyderBelserion** [comment]
Added to our suggestions board
