### ISSUE TITLE
[Bug Report] not getting any CE books from gui

### ISSUE THREAD

**Issue by IAmRyan2508** [Crazy-Crew/Crazy-Enchantments#640]
I have a wierd bug that it does let me use /ce but when i am in the gui i can just click the items in it and drag them out, i dont know how it has broken cause it was working yesterday.

**Versions (please complete the following information):**
 - Minecraft Server Version: Spiggot 1.8.9
 - Plugin Version: 1.7.9.4 (I know this isent the latest version, i have tried it with the latest version and the same problem kept happening.

**Pastebin any errors in console**
https://pastebin.com/hzdWtURs (error code)

**Issue**
Describe the issue you are having with the plugin.

**Screenshots**
[latest.log](https://github.com/Crazy-Crew/Crazy-Enchantments/files/7727480/latest.log)

**Comment by RyderBelserion** [comment]
I need a gif and your configs
