### ISSUE TITLE
CE is not Compatible with the latest Towny Version 

### ISSUE THREAD

**Issue by svdermant** [Crazy-Crew/Crazy-Enchantments#643]
read this and please update your Towny Support: https://github.com/TownyAdvanced/Towny/issues/5577#issuecomment-1002111815 Thank you.
!!!!!!!!!!!!!

**Comment by RyderBelserion** [comment]
Will update later

**Comment by svdermant** [comment]
Question: When is later with you? 3 months later? 3 years later etc? Sorry I ask but that would be the same principle if you are still programming with Java ́8 although there is already Java 16 or higher.
