### ISSUE TITLE
ArmorEquipEvent bug serverversion: 1.7.9 plugin version : 1.7.9

### ISSUE THREAD

**Issue by Jakewolfm** [Crazy-Crew/Crazy-Enchantments#649]
spams the console with this when i equip a set with customenchants
![Screenshot_79](https://user-images.githubusercontent.com/44171501/156295219-31ab5aaf-9d29-445d-88ed-41b410d04a73.png)

**Comment by RyderBelserion** [comment]
I would recommend getting off 1.7.10, We do not support a version that old and offer no bug patches.

https://papermc.io/downloads -> Please update to the latest server software or at least one of the 3 being 1.8, 1.12.2, 1.18. ( Legacy tab on PaperMC has 1.8 & 1.12.2. )

You can then grab the latest CE Builds @ https://jenkins.badbones69.com/job/Crazy-Enchantments/ which should function fine on those 3.
