### ISSUE TITLE
Players are getting the Pairing failed error when trying to apply certain enchants

### ISSUE THREAD

**Issue by oxygenmcnet** [Crazy-Crew/Crazy-Enchantments#656]
Players are getting the Pairing failed error when trying to apply certain enchants

Server Version: 1.18.1
Plugin Version: 1.8 Dev Build v12 - Build #21

Getting these errors in console every few seconds:

https://pastebin.com/jnNmqRs9

Attached is a screenshot players are getting also that I believe relates to those errors.

![2022-03-26_22](https://user-images.githubusercontent.com/102478495/160310114-b9c2adfe-5822-4f50-b85c-d11e6c1bd4a6.png)

**Comment by RyderBelserion** [comment]
Which enchants? @oxygenmcnet
