### ISSUE TITLE
[Bug Report] Enchants wont set on an item if the player is not op

### ISSUE THREAD

**Issue by Orangeeeeeeeeee** [Crazy-Crew/Crazy-Enchantments#658]
- Minecraft Server Version: [e.g. 1.8.8]
 - Plugin Version: [e.g. 1.7.9.4]
![image](https://user-images.githubusercontent.com/105062338/167151598-7e066f54-9efd-4c41-a196-92bd9a500988.png)

**Comment by RyderBelserion** [comment]
crazyenchantments.limit.# -> will increase the amount of enchantments per item.
