### ISSUE TITLE
[Bug Report] telepathy works like silk touch

### ISSUE THREAD

**Issue by edowski** [Crazy-Crew/Crazy-Enchantments#662]
**Describe the bug**
mining block with tool that has telepathy will give it

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.17.1
 - Plugin Version: v1.8-Dev-Build-v10-Build#179

**Issue**
mining stone with axe enchanted on telepathy gives you it(in stone form not cobble)

**Comment by RyderBelserion** [comment]
Added to our bug tracker.
